# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'NSDExtendTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NSDExtendTools
	pod 'AFNetworking', '~> 3.2.1'
  pod 'JSONModel', '~> 1.8.0'

end
