# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
target 'NSDExtendTools' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks

  # Pods for NSDExtendTools
	pod 'AFNetworking', '~> 3.2.1'
  pod 'ReactiveObjC', '~> 3.1.0'
  pod 'MyLayout', '~> 1.6.1'
end
